### ISSUE TITLE
Share latest source code?

### ISSUE THREAD

**Issue by cowboy** [grchld/rftg-scorer#7]
The version that I see here seems to be a bit behind the one at https://play.google.com/store/apps/details?id=org.rftg.scorer, also the version numbers appear to be very different... is this the same project?

**Comment by grchld** [comment]
Sources for version 1.4.5 (one was recently deployed on google play) are in branch old_opencv_release.

I've tried to rewrite project without OpenCV routines, thus version 2.0 appeared, but I've encountered some technical difficulties and have not enough time to solve them.

When I was asked to add Alien Artifacts cards to the project, I have to use alternative branch:
https://github.com/grchld/rftg-scorer/tree/old_opencv_release
